// GENERATED by build/build-flags.js — do not edit by hand.
export type FlagCountry =
  | "abkhazia"
  | "afghanistan"
  | "aland-islands"
  | "albania"
  | "algeria"
  | "american-samoa"
  | "andorra"
  | "angola"
  | "anguilla"
  | "antigua-and-barbuda"
  | "argentina"
  | "armenia"
  | "aruba"
  | "australia"
  | "austria"
  | "azerbaijan"
  | "azores-islands"
  | "bahamas"
  | "bahrain"
  | "balearic-islands"
  | "bangladesh"
  | "barbados"
  | "basque-country"
  | "belarus"
  | "belgium"
  | "belize"
  | "benin"
  | "bermuda"
  | "bhutan"
  | "bolivia"
  | "bonaire"
  | "bosnia-and-herzegovina"
  | "botswana"
  | "brazil"
  | "british-columbia"
  | "british-indian-ocean-territory"
  | "british-virgin-islands"
  | "brunei"
  | "bulgaria"
  | "burkina-faso"
  | "burundi"
  | "cambodia"
  | "cameroon"
  | "canada"
  | "canary-islands"
  | "cape-verde"
  | "cayman-islands"
  | "central-african-republic"
  | "ceuta"
  | "chad"
  | "chile"
  | "china"
  | "cocos-island"
  | "colombia"
  | "comoros"
  | "cook-islands"
  | "corsica"
  | "costa-rica"
  | "croatia"
  | "cuba"
  | "curacao"
  | "cyprus"
  | "czech-republic"
  | "democratic-republic-of-congo"
  | "denmark"
  | "djibouti"
  | "dominica"
  | "dominican-republic"
  | "east-timor"
  | "ecuador"
  | "egypt"
  | "el-salvador"
  | "england"
  | "equatorial-guinea"
  | "eritrea"
  | "estonia"
  | "ethiopia"
  | "european-union"
  | "falkland-islands"
  | "faroe-islands"
  | "fiji"
  | "finland"
  | "france"
  | "french-polynesia"
  | "gabon"
  | "galapagos-islands"
  | "gambia"
  | "georgia"
  | "germany"
  | "ghana"
  | "gibraltar"
  | "greece"
  | "greenland"
  | "grenada"
  | "guam"
  | "guatemala"
  | "guernsey"
  | "guinea-bissau"
  | "guinea"
  | "guyana"
  | "haiti"
  | "hawaii"
  | "honduras"
  | "hong-kong"
  | "hungary"
  | "iceland"
  | "india"
  | "indonesia"
  | "iran"
  | "iraq"
  | "ireland"
  | "isle-of-man"
  | "israel"
  | "italy"
  | "ivory-coast"
  | "jamaica"
  | "japan"
  | "jersey"
  | "jordan"
  | "kazakhstan"
  | "kenya"
  | "kiribati"
  | "kosovo"
  | "kuwait"
  | "kyrgyzstan"
  | "laos"
  | "latvia"
  | "lebanon"
  | "lesotho"
  | "liberia"
  | "libya"
  | "liechtenstein"
  | "lithuania"
  | "luxembourg"
  | "macao"
  | "madagascar"
  | "madeira"
  | "malawi"
  | "malaysia"
  | "maldives"
  | "mali"
  | "malta"
  | "marshall-island"
  | "martinique"
  | "mauritania"
  | "mauritius"
  | "melilla"
  | "mexico"
  | "micronesia"
  | "moldova"
  | "monaco"
  | "mongolia"
  | "montenegro"
  | "montserrat"
  | "morocco"
  | "mozambique"
  | "myanmar"
  | "namibia"
  | "nato"
  | "nauru"
  | "nepal"
  | "netherlands"
  | "new-zealand"
  | "nicaragua"
  | "niger"
  | "nigeria"
  | "niue"
  | "norfolk-island"
  | "north-korea"
  | "northern-cyprus"
  | "northern-marianas-islands"
  | "norway"
  | "oman"
  | "orkney-islands"
  | "ossetia"
  | "pakistan"
  | "palau"
  | "palestine"
  | "panama"
  | "papua-new-guinea"
  | "paraguay"
  | "peru"
  | "philippines"
  | "pitcairn-islands"
  | "poland"
  | "portugal"
  | "puerto-rico"
  | "qatar"
  | "rapa-nui"
  | "republic-of-macedonia"
  | "republic-of-the-congo"
  | "romania"
  | "russia"
  | "rwanda"
  | "saba-island"
  | "sahrawi-arab-democratic-republic"
  | "samoa"
  | "san-marino"
  | "sao-tome-and-prince"
  | "sardinia"
  | "saudi-arabia"
  | "scotland"
  | "senegal"
  | "serbia"
  | "seychelles"
  | "sierra-leone"
  | "singapore"
  | "sint-eustatius"
  | "sint-maarten"
  | "slovakia"
  | "slovenia"
  | "solomon-islands"
  | "somalia"
  | "somaliland"
  | "south-africa"
  | "south-korea"
  | "south-sudan"
  | "spain"
  | "sri-lanka"
  | "st-barts"
  | "st-lucia"
  | "st-vincent-and-the-grenadines"
  | "sudan"
  | "suriname"
  | "swaziland"
  | "sweden"
  | "switzerland"
  | "syria"
  | "taiwan"
  | "tajikistan"
  | "tanzania"
  | "thailand"
  | "tibet"
  | "togo"
  | "tokelau"
  | "tonga"
  | "transnistria"
  | "trinidad-and-tobago"
  | "tunisia"
  | "turkey"
  | "turkmenistan"
  | "turks-and-caicos"
  | "tuvalu"
  | "uganda"
  | "ukraine"
  | "united-arab-emirates"
  | "united-kingdom"
  | "united-nations"
  | "united-states"
  | "uruguay"
  | "uzbekistan"
  | "vanuatu"
  | "vatican-city"
  | "venezuela"
  | "vietnam"
  | "virgin-islands"
  | "wales"
  | "yemen"
  | "zambia"
  | "zimbabwe";

export const FLAG_COUNTRIES: FlagCountry[] = [
  "abkhazia",
  "afghanistan",
  "aland-islands",
  "albania",
  "algeria",
  "american-samoa",
  "andorra",
  "angola",
  "anguilla",
  "antigua-and-barbuda",
  "argentina",
  "armenia",
  "aruba",
  "australia",
  "austria",
  "azerbaijan",
  "azores-islands",
  "bahamas",
  "bahrain",
  "balearic-islands",
  "bangladesh",
  "barbados",
  "basque-country",
  "belarus",
  "belgium",
  "belize",
  "benin",
  "bermuda",
  "bhutan",
  "bolivia",
  "bonaire",
  "bosnia-and-herzegovina",
  "botswana",
  "brazil",
  "british-columbia",
  "british-indian-ocean-territory",
  "british-virgin-islands",
  "brunei",
  "bulgaria",
  "burkina-faso",
  "burundi",
  "cambodia",
  "cameroon",
  "canada",
  "canary-islands",
  "cape-verde",
  "cayman-islands",
  "central-african-republic",
  "ceuta",
  "chad",
  "chile",
  "china",
  "cocos-island",
  "colombia",
  "comoros",
  "cook-islands",
  "corsica",
  "costa-rica",
  "croatia",
  "cuba",
  "curacao",
  "cyprus",
  "czech-republic",
  "democratic-republic-of-congo",
  "denmark",
  "djibouti",
  "dominica",
  "dominican-republic",
  "east-timor",
  "ecuador",
  "egypt",
  "el-salvador",
  "england",
  "equatorial-guinea",
  "eritrea",
  "estonia",
  "ethiopia",
  "european-union",
  "falkland-islands",
  "faroe-islands",
  "fiji",
  "finland",
  "france",
  "french-polynesia",
  "gabon",
  "galapagos-islands",
  "gambia",
  "georgia",
  "germany",
  "ghana",
  "gibraltar",
  "greece",
  "greenland",
  "grenada",
  "guam",
  "guatemala",
  "guernsey",
  "guinea-bissau",
  "guinea",
  "guyana",
  "haiti",
  "hawaii",
  "honduras",
  "hong-kong",
  "hungary",
  "iceland",
  "india",
  "indonesia",
  "iran",
  "iraq",
  "ireland",
  "isle-of-man",
  "israel",
  "italy",
  "ivory-coast",
  "jamaica",
  "japan",
  "jersey",
  "jordan",
  "kazakhstan",
  "kenya",
  "kiribati",
  "kosovo",
  "kuwait",
  "kyrgyzstan",
  "laos",
  "latvia",
  "lebanon",
  "lesotho",
  "liberia",
  "libya",
  "liechtenstein",
  "lithuania",
  "luxembourg",
  "macao",
  "madagascar",
  "madeira",
  "malawi",
  "malaysia",
  "maldives",
  "mali",
  "malta",
  "marshall-island",
  "martinique",
  "mauritania",
  "mauritius",
  "melilla",
  "mexico",
  "micronesia",
  "moldova",
  "monaco",
  "mongolia",
  "montenegro",
  "montserrat",
  "morocco",
  "mozambique",
  "myanmar",
  "namibia",
  "nato",
  "nauru",
  "nepal",
  "netherlands",
  "new-zealand",
  "nicaragua",
  "niger",
  "nigeria",
  "niue",
  "norfolk-island",
  "north-korea",
  "northern-cyprus",
  "northern-marianas-islands",
  "norway",
  "oman",
  "orkney-islands",
  "ossetia",
  "pakistan",
  "palau",
  "palestine",
  "panama",
  "papua-new-guinea",
  "paraguay",
  "peru",
  "philippines",
  "pitcairn-islands",
  "poland",
  "portugal",
  "puerto-rico",
  "qatar",
  "rapa-nui",
  "republic-of-macedonia",
  "republic-of-the-congo",
  "romania",
  "russia",
  "rwanda",
  "saba-island",
  "sahrawi-arab-democratic-republic",
  "samoa",
  "san-marino",
  "sao-tome-and-prince",
  "sardinia",
  "saudi-arabia",
  "scotland",
  "senegal",
  "serbia",
  "seychelles",
  "sierra-leone",
  "singapore",
  "sint-eustatius",
  "sint-maarten",
  "slovakia",
  "slovenia",
  "solomon-islands",
  "somalia",
  "somaliland",
  "south-africa",
  "south-korea",
  "south-sudan",
  "spain",
  "sri-lanka",
  "st-barts",
  "st-lucia",
  "st-vincent-and-the-grenadines",
  "sudan",
  "suriname",
  "swaziland",
  "sweden",
  "switzerland",
  "syria",
  "taiwan",
  "tajikistan",
  "tanzania",
  "thailand",
  "tibet",
  "togo",
  "tokelau",
  "tonga",
  "transnistria",
  "trinidad-and-tobago",
  "tunisia",
  "turkey",
  "turkmenistan",
  "turks-and-caicos",
  "tuvalu",
  "uganda",
  "ukraine",
  "united-arab-emirates",
  "united-kingdom",
  "united-nations",
  "united-states",
  "uruguay",
  "uzbekistan",
  "vanuatu",
  "vatican-city",
  "venezuela",
  "vietnam",
  "virgin-islands",
  "wales",
  "yemen",
  "zambia",
  "zimbabwe",
];

// Straight Title Case of the slug — good enough for a picker label; a few
// entries (e.g. "Nato") read better as an acronym than this produces, but
// that's a cosmetic gap not worth hand-listing exceptions for 260 entries.
export const FLAG_LABELS: Record<FlagCountry, string> = {
  "abkhazia": "Abkhazia",
  "afghanistan": "Afghanistan",
  "aland-islands": "Aland Islands",
  "albania": "Albania",
  "algeria": "Algeria",
  "american-samoa": "American Samoa",
  "andorra": "Andorra",
  "angola": "Angola",
  "anguilla": "Anguilla",
  "antigua-and-barbuda": "Antigua And Barbuda",
  "argentina": "Argentina",
  "armenia": "Armenia",
  "aruba": "Aruba",
  "australia": "Australia",
  "austria": "Austria",
  "azerbaijan": "Azerbaijan",
  "azores-islands": "Azores Islands",
  "bahamas": "Bahamas",
  "bahrain": "Bahrain",
  "balearic-islands": "Balearic Islands",
  "bangladesh": "Bangladesh",
  "barbados": "Barbados",
  "basque-country": "Basque Country",
  "belarus": "Belarus",
  "belgium": "Belgium",
  "belize": "Belize",
  "benin": "Benin",
  "bermuda": "Bermuda",
  "bhutan": "Bhutan",
  "bolivia": "Bolivia",
  "bonaire": "Bonaire",
  "bosnia-and-herzegovina": "Bosnia And Herzegovina",
  "botswana": "Botswana",
  "brazil": "Brazil",
  "british-columbia": "British Columbia",
  "british-indian-ocean-territory": "British Indian Ocean Territory",
  "british-virgin-islands": "British Virgin Islands",
  "brunei": "Brunei",
  "bulgaria": "Bulgaria",
  "burkina-faso": "Burkina Faso",
  "burundi": "Burundi",
  "cambodia": "Cambodia",
  "cameroon": "Cameroon",
  "canada": "Canada",
  "canary-islands": "Canary Islands",
  "cape-verde": "Cape Verde",
  "cayman-islands": "Cayman Islands",
  "central-african-republic": "Central African Republic",
  "ceuta": "Ceuta",
  "chad": "Chad",
  "chile": "Chile",
  "china": "China",
  "cocos-island": "Cocos Island",
  "colombia": "Colombia",
  "comoros": "Comoros",
  "cook-islands": "Cook Islands",
  "corsica": "Corsica",
  "costa-rica": "Costa Rica",
  "croatia": "Croatia",
  "cuba": "Cuba",
  "curacao": "Curacao",
  "cyprus": "Cyprus",
  "czech-republic": "Czech Republic",
  "democratic-republic-of-congo": "Democratic Republic Of Congo",
  "denmark": "Denmark",
  "djibouti": "Djibouti",
  "dominica": "Dominica",
  "dominican-republic": "Dominican Republic",
  "east-timor": "East Timor",
  "ecuador": "Ecuador",
  "egypt": "Egypt",
  "el-salvador": "El Salvador",
  "england": "England",
  "equatorial-guinea": "Equatorial Guinea",
  "eritrea": "Eritrea",
  "estonia": "Estonia",
  "ethiopia": "Ethiopia",
  "european-union": "European Union",
  "falkland-islands": "Falkland Islands",
  "faroe-islands": "Faroe Islands",
  "fiji": "Fiji",
  "finland": "Finland",
  "france": "France",
  "french-polynesia": "French Polynesia",
  "gabon": "Gabon",
  "galapagos-islands": "Galapagos Islands",
  "gambia": "Gambia",
  "georgia": "Georgia",
  "germany": "Germany",
  "ghana": "Ghana",
  "gibraltar": "Gibraltar",
  "greece": "Greece",
  "greenland": "Greenland",
  "grenada": "Grenada",
  "guam": "Guam",
  "guatemala": "Guatemala",
  "guernsey": "Guernsey",
  "guinea-bissau": "Guinea Bissau",
  "guinea": "Guinea",
  "guyana": "Guyana",
  "haiti": "Haiti",
  "hawaii": "Hawaii",
  "honduras": "Honduras",
  "hong-kong": "Hong Kong",
  "hungary": "Hungary",
  "iceland": "Iceland",
  "india": "India",
  "indonesia": "Indonesia",
  "iran": "Iran",
  "iraq": "Iraq",
  "ireland": "Ireland",
  "isle-of-man": "Isle Of Man",
  "israel": "Israel",
  "italy": "Italy",
  "ivory-coast": "Ivory Coast",
  "jamaica": "Jamaica",
  "japan": "Japan",
  "jersey": "Jersey",
  "jordan": "Jordan",
  "kazakhstan": "Kazakhstan",
  "kenya": "Kenya",
  "kiribati": "Kiribati",
  "kosovo": "Kosovo",
  "kuwait": "Kuwait",
  "kyrgyzstan": "Kyrgyzstan",
  "laos": "Laos",
  "latvia": "Latvia",
  "lebanon": "Lebanon",
  "lesotho": "Lesotho",
  "liberia": "Liberia",
  "libya": "Libya",
  "liechtenstein": "Liechtenstein",
  "lithuania": "Lithuania",
  "luxembourg": "Luxembourg",
  "macao": "Macao",
  "madagascar": "Madagascar",
  "madeira": "Madeira",
  "malawi": "Malawi",
  "malaysia": "Malaysia",
  "maldives": "Maldives",
  "mali": "Mali",
  "malta": "Malta",
  "marshall-island": "Marshall Island",
  "martinique": "Martinique",
  "mauritania": "Mauritania",
  "mauritius": "Mauritius",
  "melilla": "Melilla",
  "mexico": "Mexico",
  "micronesia": "Micronesia",
  "moldova": "Moldova",
  "monaco": "Monaco",
  "mongolia": "Mongolia",
  "montenegro": "Montenegro",
  "montserrat": "Montserrat",
  "morocco": "Morocco",
  "mozambique": "Mozambique",
  "myanmar": "Myanmar",
  "namibia": "Namibia",
  "nato": "Nato",
  "nauru": "Nauru",
  "nepal": "Nepal",
  "netherlands": "Netherlands",
  "new-zealand": "New Zealand",
  "nicaragua": "Nicaragua",
  "niger": "Niger",
  "nigeria": "Nigeria",
  "niue": "Niue",
  "norfolk-island": "Norfolk Island",
  "north-korea": "North Korea",
  "northern-cyprus": "Northern Cyprus",
  "northern-marianas-islands": "Northern Marianas Islands",
  "norway": "Norway",
  "oman": "Oman",
  "orkney-islands": "Orkney Islands",
  "ossetia": "Ossetia",
  "pakistan": "Pakistan",
  "palau": "Palau",
  "palestine": "Palestine",
  "panama": "Panama",
  "papua-new-guinea": "Papua New Guinea",
  "paraguay": "Paraguay",
  "peru": "Peru",
  "philippines": "Philippines",
  "pitcairn-islands": "Pitcairn Islands",
  "poland": "Poland",
  "portugal": "Portugal",
  "puerto-rico": "Puerto Rico",
  "qatar": "Qatar",
  "rapa-nui": "Rapa Nui",
  "republic-of-macedonia": "Republic Of Macedonia",
  "republic-of-the-congo": "Republic Of The Congo",
  "romania": "Romania",
  "russia": "Russia",
  "rwanda": "Rwanda",
  "saba-island": "Saba Island",
  "sahrawi-arab-democratic-republic": "Sahrawi Arab Democratic Republic",
  "samoa": "Samoa",
  "san-marino": "San Marino",
  "sao-tome-and-prince": "Sao Tome And Prince",
  "sardinia": "Sardinia",
  "saudi-arabia": "Saudi Arabia",
  "scotland": "Scotland",
  "senegal": "Senegal",
  "serbia": "Serbia",
  "seychelles": "Seychelles",
  "sierra-leone": "Sierra Leone",
  "singapore": "Singapore",
  "sint-eustatius": "Sint Eustatius",
  "sint-maarten": "Sint Maarten",
  "slovakia": "Slovakia",
  "slovenia": "Slovenia",
  "solomon-islands": "Solomon Islands",
  "somalia": "Somalia",
  "somaliland": "Somaliland",
  "south-africa": "South Africa",
  "south-korea": "South Korea",
  "south-sudan": "South Sudan",
  "spain": "Spain",
  "sri-lanka": "Sri Lanka",
  "st-barts": "St Barts",
  "st-lucia": "St Lucia",
  "st-vincent-and-the-grenadines": "St Vincent And The Grenadines",
  "sudan": "Sudan",
  "suriname": "Suriname",
  "swaziland": "Swaziland",
  "sweden": "Sweden",
  "switzerland": "Switzerland",
  "syria": "Syria",
  "taiwan": "Taiwan",
  "tajikistan": "Tajikistan",
  "tanzania": "Tanzania",
  "thailand": "Thailand",
  "tibet": "Tibet",
  "togo": "Togo",
  "tokelau": "Tokelau",
  "tonga": "Tonga",
  "transnistria": "Transnistria",
  "trinidad-and-tobago": "Trinidad And Tobago",
  "tunisia": "Tunisia",
  "turkey": "Turkey",
  "turkmenistan": "Turkmenistan",
  "turks-and-caicos": "Turks And Caicos",
  "tuvalu": "Tuvalu",
  "uganda": "Uganda",
  "ukraine": "Ukraine",
  "united-arab-emirates": "United Arab Emirates",
  "united-kingdom": "United Kingdom",
  "united-nations": "United Nations",
  "united-states": "United States",
  "uruguay": "Uruguay",
  "uzbekistan": "Uzbekistan",
  "vanuatu": "Vanuatu",
  "vatican-city": "Vatican City",
  "venezuela": "Venezuela",
  "vietnam": "Vietnam",
  "virgin-islands": "Virgin Islands",
  "wales": "Wales",
  "yemen": "Yemen",
  "zambia": "Zambia",
  "zimbabwe": "Zimbabwe",
};
